add fixing of kernel/scini.ko problem to fuel emulator

diff --git a/juju/functions b/juju/functions
--- a/juju/functions
+++ b/juju/functions
@@ -67,20 +67,20 @@ function get_cluster_mode() {
 }
 
 function wait_for_machines() {
-  echo "Wait for machines"
-  for mch in $@ ; do
-    iter=0
-    while ! juju status | grep "\"$mch\"" &>/dev/null ; do
-      echo "Waiting for machine $mch - $iter/12"
-      if ((iter >= 12)); then
-        echo "ERROR: Machine $mch didn't up."
-        juju status
+  # wait for machines
+  sleep 30
+  for machine in $@ ; do
+    echo "Waiting for machine: $machine"
+    local fail=0
+    while ! output=`juju ssh $machine "sudo apt-get install -fy joe" 2>/dev/null` ; do
+      if ((fail >= 12)); then
+        echo "ERROR: Machine $machine did not up."
+        echo $output
         exit 1
       fi
-      ((++iter))
       sleep 10
+      ((++fail))
     done
+    juju ssh $machine uname -a 2>/dev/null
   done
-  echo "Post-Wait for machines for 30 seconds"
-  sleep 30
 }
