add waiting for machines in check-protection-domains

diff --git a/juju/functions b/juju/functions
--- a/juju/functions
+++ b/juju/functions
@@ -54,3 +54,22 @@ function get_master_mdm() {
 function get_cluster_mode() {
   juju get scaleio-mdm | grep -A 5 cluster-mode | grep "value:" | head -1 | awk '{print $2}'
 }
+
+function wait_for_machines() {
+  echo "Wait for machines"
+  for mch in $@ ; do
+    iter=0
+    while ! juju status | grep "\"$mch\"" &>/dev/null ; do
+      echo "Waiting for machine $mch - $iter/12"
+      if ((iter >= 12)); then
+        echo "ERROR: Machine $mch didn't up."
+        juju status
+        exit 1
+      fi
+      ((++iter))
+      sleep 10
+    done
+  done
+  echo "Post-Wait for machines for 30 seconds"
+  sleep 30
+}
