added test to check parameter existing-cluster=true

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -198,7 +198,8 @@ function configure_cluster() {
   fi
 
   metadata_enable=`get_config fuel-master metadata-enable`
-  if [[ $metadata_enable == '"true"' ]] ; then
+  existing_cluster=`get_config fuel-master existing-cluster`
+  if [[ $metadata_enable == '"true"' && $existing_cluster == '"false"' ]] ; then
     # check query_cluster output before exit on error if exists
     master_mdm=`get_master_mdm "echo $mdms"`
     echo "INFO: query cluster on machine $master_mdm"
@@ -531,3 +532,79 @@ function check_scaleio_not_installed {
     echo "INFO: Success. ScaleIO packages wasn't installed to controller."
   fi
 }
+
+function check_existing_cluster {
+  mdm=`get_master_mdm`
+  sdc_nodes=`echo $1 | sed 's/,/ /g'`
+
+  cluster_mdm_ips=(`juju ssh $mdm "scli --query_cluster --approve_certificate" 2>/dev/null | awk '/Management IPs/{print$5}' | sed 's/,//g'`)
+
+  for node in $sdc_nodes ; do
+    sdc=${machines[$node]}
+    #check emc-packages"
+    if output=`juju ssh $sdc "dpkg -l emc*" 2>/dev/null | grep emc | grep -v 'scaleio-sdc'` ; then
+      echo "ERROR: There is scaleio packages on machine $sdc besides scaleio-sdc."
+      echo $output
+      return 1
+    else
+      echo "INFO: Success. There is no scaleio packages on machine $sdc besides scaleio-sdc."
+    fi
+
+    sdc_mdm_ips=(`juju ssh $sdc "sudo /bin/emc/scaleio/drv_cfg --query_mdms" 2>/dev/null | awk '/MDM-ID/{print$10}' | sed 's/\[0\]-//g'`)
+
+    #check MDM addresses"
+    if [[ ${#cluster_mdm_ips[@]} != ${#sdc_mdm_ips[@]} ]] ; then
+      echo "ERROR: Wrong MDM number on SDC node $sdc. Expected ${#cluster_mdm_ips[@]}, but got ${#sdc_mdm_ips[@]}."
+      return 1
+    fi
+
+    ret=0
+    for ip in $cluster_mdm_ips ; do
+      if ! [[ ${sdc_mdm_ips[@]} =~ $ip ]] ; then
+        echo "ERROR: There is no MDM with ip $ip in cluster, but it presents on machine $sdc."
+        ((++ret))
+      fi
+    done
+
+    if [[ $ret == 0 ]] ; then
+      echo "INFO: Success. The SDC node $sdc has information about MDMs in cluster."
+    else
+      return $ret
+    fi
+
+    mdm_ip=${cluster_mdm_ips[0]}
+
+    juju ssh $sdc "sudo apt-get install emc-scaleio-mdm" 2>/dev/null
+
+    password=`get_config fuel-master password`
+    login_cmd="scli --mdm_ip $mdm_ip --login --username $username --password $password --approve_certificate"
+
+    pd_name=`juju ssh $mdm "$login_cmd && scli --query_properties --all_objects --object_type PROTECTION_DOMAIN --properties NAME" 2>/dev/null | awk '/NAME/{print$2}' | sed 's/\r//g'`
+    sp_name=`juju ssh $mdm "$login_cmd && scli --query_properties --all_objects --object_type STORAGE_POOL --properties NAME" 2>/dev/null | awk '/NAME/{print$2}' | sed 's/\r//g'`
+
+    #create volume
+    volume_name=vol$sdc
+    add_volume_cmd="scli --mdm_ip $mdm_ip --add_volume --protection_domain_name $pd_name --storage_pool_name $sp_name --size_gb 8 --volume_name $volume_name"
+    if ! juju ssh $sdc "$login_cmd && $add_volume_cmd" 2>/dev/null ; then
+      echo "ERROR: Couldn't create volume $volume_name on SDC node $sdc."
+      return 1
+    fi
+
+    #map volume
+    sdc_ip=`juju ssh $sdc "ip addr show dev eth0" 2>/dev/null | awk '/inet /{split($2,a,"/"); print a[1]}'`
+    map_volume_cmd="scli --mdm_ip $mdm_ip --map_volume_to_sdc --volume_name $volume_name --sdc_ip $sdc_ip"
+    if ! juju ssh $sdc "$login_cmd && $map_volume_cmd" 2>/dev/null ; then
+      echo "ERROR: Couldn't map volume $volume_name on SDC node $sdc."
+      return 1
+    fi
+
+    #check volumes
+    query_cmd="scli --mdm_ip $mdm_ip --query_all_volumes"
+    if juju ssh $sdc "$login_cmd && $query_cmd" 2>/dev/null | grep $volume_name | grep "Mapped to" ; then
+      echo "INFO: Success. The volume $volume_name was created and mapped on SDC node $sdc."
+    else
+      echo "ERROR: There is no mapped volume $volume_name in cluster."
+    fi
+  done
+}
+
