minor fixes in checking IP roles on SDS

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -624,12 +624,8 @@ function check_sds_ip_roles {
   all_sds_output=`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null`
   for sds_name in $(echo "$all_sds_output" | awk '/SDS ID/{print $5}') ; do
     node_details=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
-    if ! node_roles=`echo "$node_details" | grep "Role:" | grep "$expected_roles"` ; then
-      echo "ERROR: SDS $sds_name does not contain required roles (SDS and SDC) $expected_roles."
-      echo "$node_details"
-      ((++ret))
-    elif ! [[ "$node_roles" =~ 'SDC' && "$node_roles" =~ 'SDS' ]]  ; then
-      echo "ERROR: SDS $sds_name does not contain required roles."
+    if ! node_roles=`echo "$node_details" | grep " Role: $expected_roles"` ; then
+      echo "ERROR: SDS $sds_name does not contain required roles $expected_roles."
       echo "$node_details"
       ((++ret))
     else
