edit indents, changed back instance type

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -12,11 +12,11 @@ cd fuel-charms
 
 cloud=${1:-"ec2"}
 if [[ "${cloud}" == "gce" ]]; then
-    instance_type="n1-standard-1"
-    device_paths="/var/scaleio_disk"
+  instance_type="n1-standard-1"
+  device_paths="/var/scaleio_disk"
 else
-    instance_type="r3.large"
-    device_paths="/dev/xvdf"
+  instance_type="i2.2xlarge"
+  device_paths="/dev/xvdb"
 fi
 machines=()
 deploy_counter=1
@@ -24,270 +24,267 @@ deploy_counter=1
 trap 'catch_errors $LINENO' ERR
 
 function provision_machines() {
-    local new_mx=()
-    echo "Provision machines: $*"
-    while (( "$#" )); do
-      disks=''
-      da=()
-      for (( i=0; i<2; ++i)) ; do da=(${da[@]} ebs-ssd,100G) ; done
-      disks="${da[@]}"
-      local mx=$(juju machine add --constraints "instance-type=${instance_type} root-disk=40G" --disks "$disks" 2>&1 | awk '{print $3}')
-      echo "Machine $1 created: $mx"
-      machines[$1]=${mx}
-      new_mx+=(${mx})
-      shift
+  local new_mx=()
+  echo "Provision machines: $*"
+  while (( "$#" )); do
+    local mx=$(juju add-machine --constraints "instance-type=${instance_type}" 2>&1 | awk '{print $3}')
+#    local mx=$(create_machine 2 2)
+    echo "Machine $1 created: $mx"
+    machines[$1]=${mx}
+    new_mx+=(${mx})
+    shift
+  done
+
+  # wait for machines up
+  wait_for_machines ${new_mx[@]}
+
+  # if not EC2:
+  #       - prepare device for SDS (truncated file)
+  #       - patch host name - in GCE hostname is too long, e.g. juju-023fae94-ef89-4b6d-8681-d9e462c7fae3-machine-2
+  if [[ "${cloud}" == "gce" ]]; then
+    for i in ${new_mx[@]}; do
+      paths=$(echo ${device_paths} | sed 's/,/ /g')
+      juju ssh $i "for p in ${paths}; do sudo rm -f \$p && sudo truncate --size 100G \$p; done"
+      juju ssh $i "sudo sed -i 's/\(juju-\)\(.*\)\(machine.*\)/\1\3/g' /etc/hostname && sudo hostname -F /etc/hostname"
+    done
+  fi
+
+  # check kernel at one machine
+  rm -f index.html
+  wget -t 2 -T 30 -nv "--ftp-user=QNzgdxXix" "--ftp-password=Aw3wFAwAq3" ftp://ftp.emc.com/Ubuntu/2.0.5014.0/
+  kernel=`juju ssh ${new_mx[0]} "uname -r" 2>/dev/null`
+  kernel=`echo $kernel | sed 's/\r//'`
+  if ! cat index.html | grep $kernel ; then
+    echo "WARNING: driver for kernel $kernel not found on ftp.emc.com. Upgrade kernel to 4.2.0-30"
+
+    # change kernel and reboot
+    for m in ${new_mx[@]} ; do
+      echo "--- Updating machine $m"
+      juju ssh $m "sudo apt-get install -fy linux-image-4.2.0-30-generic linux-headers-4.2.0-30-generic &>/dev/null" 2>/dev/null
+      juju ssh $m "sudo reboot" 2>/dev/null
     done
 
     # wait for machines up
     wait_for_machines ${new_mx[@]}
+  fi
+  rm -f index.html
 
-    # if not EC2:
-    #       - prepare device for SDS (truncated file)
-    #       - patch host name - in GCE hostname is too long, e.g. juju-023fae94-ef89-4b6d-8681-d9e462c7fae3-machine-2
-    if [[ "${cloud}" == "gce" ]]; then
-        for i in ${new_mx[@]}; do
-            paths=$(echo ${device_paths} | sed 's/,/ /g')
-            juju ssh $i "for p in ${paths}; do sudo rm -f \$p && sudo truncate --size 100G \$p; done" 2>/dev/null
-            juju ssh $i "sudo sed -i 's/\(juju-\)\(.*\)\(machine.*\)/\1\3/g' /etc/hostname && sudo hostname -F /etc/hostname" 2>/dev/null
-        done
-    fi
-
-    # check kernel at one machine
-    rm -f index.html
-    wget -t 2 -T 30 -nv "--ftp-user=QNzgdxXix" "--ftp-password=Aw3wFAwAq3" ftp://ftp.emc.com/Ubuntu/2.0.5014.0/
-    kernel=`juju ssh ${new_mx[0]} "uname -r" 2>/dev/null`
-    kernel=`echo $kernel | sed 's/\r//'`
-    if ! cat index.html | grep $kernel ; then
-      echo "WARNING: driver for kernel $kernel not found on ftp.emc.com. Upgrade kernel to 4.2.0-30"
-
-      # change kernel and reboot
-      for m in ${new_mx[@]} ; do
-        echo "--- Updating machine $m"
-        juju ssh $m "sudo apt-get install -fy linux-image-4.2.0-30-generic linux-headers-4.2.0-30-generic &>/dev/null" 2>/dev/null
-        juju ssh $m "sudo reboot" 2>/dev/null
-      done
-
-      # wait for machines up
-      wait_for_machines ${new_mx[@]}
-    fi
-    rm -f index.html
-
-    # deploy fake module to avoid removal of machines in case of remove last service
-    for i in ${new_mx[@]}; do
-        juju deploy ubuntu fuel-null-service${i} --to ${i}
-    done
+  # deploy fake module to avoid removal of machines in case of remove last service
+  for i in ${new_mx[@]}; do
+    juju deploy ubuntu fuel-null-service${i} --to ${i}
+  done
 }
 
 function copy_log() {
-    mch=$1
-    log=$2
-    dst=$3
-    if juju ssh $mch "test -f $log" ; then
-        juju ssh $mch "cat $log" > "$dst" 2>/dev/null
-    fi
+  mch=$1
+  log=$2
+  dst=$3
+  if juju ssh $mch "test -f $log" ; then
+    juju ssh $mch "cat $log" > "$dst" 2>/dev/null
+  fi
 }
 
 function save_logs() {
-    # save status to file
-    for mch in ${machines[@]:1} ; do
-        name=fuel-node${mch}
-        if juju service get ${name} >/dev/null ; then
-            mdir="$cdir/logs/$mch"
-            mkdir -p "$mdir"
-            copy_log $mch '/var/log/fuel-puppet-scaleio.log' "$mdir/fuel-puppet-scaleio.log"
-            copy_log $mch '/var/lib/hiera/defaults.yaml' "$mdir/var-lib-hiera-defaults.log"
-        fi
-    done
+  # save status to file
+  for mch in ${machines[@]:1} ; do
+    name=fuel-node${mch}
+    if juju service get ${name} ; then
+      mdir="$cdir/logs/$mch"
+      mkdir -p "$mdir"
+      copy_log $mch '/var/log/fuel-puppet-scaleio.log' "$mdir/fuel-puppet-scaleio.log"
+      copy_log $mch '/var/lib/hiera/defaults.yaml' "$mdir/var-lib-hiera-defaults.log"
+    fi
+  done
 }
 
 function catch_errors() {
-    local exit_code=$?
-    echo "Line: $1  Error=$exit_code  Command: '$BASH_COMMAND'"
-    trap - ERR
-    save_logs
-    exit $exit_code
+  local exit_code=$?
+  echo "Line: $1  Error=$exit_code  Command: '$BASH_COMMAND'"
+  trap - ERR
+  save_logs
+  exit $exit_code
 }
 
 function remove_node_service() {
-    echo Remove service from machines $@
-    machs="$#"
-    while (( "$#" )); do
-        mch=${machines[$1]}
-        name=fuel-node${mch}
-        echo Remove EMC packages from machine $1/$machs
-        juju ssh $mch 'sudo truncate --size 0 /etc/environment && sudo apt-get purge -yf emc-scaleio-*' >/dev/null
-        echo Remove service ${name} from machine $1/$machs
-        juju remove-service ${name} >/dev/null
-        shift
-    done
+  echo Remove service from machines $@
+  machs="$#"
+  while (( "$#" )); do
+    mch=${machines[$1]}
+    name=fuel-node${mch}
+    echo Remove EMC packages from machine $1/$machs
+    juju ssh $mch 'sudo truncate --size 0 /etc/environment && sudo apt-get purge -yf emc-scaleio-*'
+    echo Remove service ${name} from machine $1/$machs
+    juju remove-service ${name}
+    shift
+  done
 }
 
 function prepare_fuel_master() {
-    mch=${machines[$1]}
-    juju deploy local:trusty/fuel-master --to ${mch}
-    juju set fuel-master device-paths=${device_paths}
+  mch=${machines[$1]}
+  juju deploy local:trusty/fuel-master --to $mch
+  juju set fuel-master device-paths=${device_paths}
 }
 
 function set_fuel_options() {
-    juju set fuel-master $*
+  juju set fuel-master $*
 }
 
 function deploy_node_service() {
-    mch=${machines[$1]}
-    name=fuel-node${mch}
-    roles=$2
-    if ! juju service get ${name} 2>/dev/null ; then
-        juju deploy local:trusty/fuel-node $name --to $mch
-        juju add-relation fuel-master $name
-    fi
-    juju set $name roles="${roles}"
+  mch=${machines[$1]}
+  name=fuel-node${mch}
+  roles=$2
+  if ! juju service get ${name} ; then
+    juju deploy local:trusty/fuel-node $name --to $mch
+    juju add-relation fuel-master $name
+  fi
+  juju set $name roles="${roles}"
 }
 
 function configure_cluster() {
-    mdms=""
-    while (( "$#" )); do
-        case "$1" in
-            "compute")
-                shift
-                for i in `echo $1 | sed 's/,/ /g'`; do
-                    deploy_node_service $i "compute"
-                done
-            ;;
-            "primary-controller")
-                shift
-                deploy_node_service $1 "primary-controller cinder"
-                mdms+=" ${machines[$1]}"
-            ;;
-            "controller")
-                shift
-                for i in `echo $1 | sed 's/,/ /g'`; do
-                    deploy_node_service $i "controller cinder"
-                    mdms+=" ${machines[$i]}"
-                done
-            ;;
-            "mode")
-                shift
-                mode=$1
-            ;;
-        esac
+  mdms=""
+  while (( "$#" )); do
+    case "$1" in
+      "compute")
         shift
-    done
+        for i in `echo $1 | sed 's/,/ /g'`; do
+          deploy_node_service $i "compute"
+        done
+      ;;
+      "primary-controller")
+        shift
+        deploy_node_service $1 "primary-controller cinder"
+        mdms+=" ${machines[$1]}"
+      ;;
+      "controller")
+        shift
+        for i in `echo $1 | sed 's/,/ /g'`; do
+          deploy_node_service $i "controller cinder"
+          mdms+=" ${machines[$i]}"
+        done
+      ;;
+      "mode")
+        shift
+        mode=$1
+      ;;
+    esac
+    shift
+  done
 
-    sleep 15
+  sleep 15
 
-    echo "Wait for services start: $(date)"
-    wait_absence_status_for_services "executing|blocked|waiting|allocating"
-    echo "Wait for services end: $(date)"
+  echo "Wait for services start: $(date)"
+  wait_absence_status_for_services "executing|blocked|waiting|allocating"
+  echo "Wait for services end: $(date)"
 
-    juju set fuel-master deploy=$deploy_counter
-    ((deploy_counter++))
-    sleep 30
+  juju set fuel-master deploy=$deploy_counter
+  ((deploy_counter++))
+  sleep 30
 
-    echo "Wait for services start: $(date)"
-    wait_absence_status_for_services "maintenance"
-    echo "Wait for services end: $(date)"
+  echo "Wait for services start: $(date)"
+  wait_absence_status_for_services "maintenance"
+  echo "Wait for services end: $(date)"
 
-    # check query_cluster output before exit on error if exists
-    master_mdm=`get_master_mdm "echo $mdms"`
-    echo "INFO: query cluster on machine $master_mdm"
-    juju ssh $master_mdm 'scli --query_cluster --approve_certificate' 2>/dev/null
+  # check query_cluster output before exit on error if exists
+  master_mdm=`get_master_mdm "echo $mdms"`
+  echo "INFO: query cluster on machine $master_mdm"
+  juju ssh $master_mdm 'scli --query_cluster --approve_certificate' 2>/dev/null
 
-    # check for errors
-    if juju status | grep "current" | grep error ; then
-      echo "ERROR: Some services went to error state"
-      juju ssh 0 sudo grep Error /var/log/juju/all-machines.log 2>/dev/null
-      exit 1
-    fi
+  # check for errors
+  if juju status | grep "current" | grep error ; then
+    echo "ERROR: Some services went to error state"
+    juju ssh 0 sudo grep Error /var/log/juju/all-machines.log 2>/dev/null
+    exit 1
+  fi
 
-    check-cluster "juju ssh" $master_mdm $mode
+  check-cluster "juju ssh" $master_mdm $mode
 }
 
 #TODO: remove duplication of code: re-use the check functions from common code when it appears
 function check_storage_pool {
-    local mch=${machines[$1]}
-    local key_to_check=$2
-    local expected_value=$3
+  mch=${machines[$1]}
+  key_to_check=$2
+  expected_value=$3
 
-    local sp=`get_config storage-pools`
-    local pd=`get_config protection-domain`
-    local username='admin'
-    local password=`get_config password`
+  sp=`get_config fuel-master storage-pools`
+  pd=`get_config fuel-master protection-domain`
+  username='admin'
+  password=`get_config fuel-master password`
 
-    local login_cmd="scli --login --username $username --password $password --approve_certificate >/dev/null"
-    local query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
-    juju ssh $mch "$login_cmd && $query_cmd" | grep "$key_to_check" | grep -q "$expected_value" >/dev/null
-    echo "INFO: Success. Parameter $key_to_check is $expected_value."
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+  juju ssh $mch "$login_cmd && $query_cmd" | grep "$key_to_check" | grep -q "$expected_value"
+  echo "INFO: Success. Parameter $key_to_check is $expected_value."
 }
 
 function check_capacity_alerts {
-    local mch=${machines[$1]}
-    local high_alert=$2
-    local critical_alert=$3
+  mch=${machines[$1]}
+  high_alert=$2
+  critical_alert=$3
 
-    local sp=`get_config storage-pools`
-    local pd=`get_config protection-domain`
-    local username='admin'
-    local password=`get_config password`
+  sp=`get_config fuel-master storage-pools`
+  pd=`get_config fuel-master protection-domain`
+  username='admin'
+  password=`get_config fuel-master password`
 
-    local login_cmd="scli --login --username $username --password $password --approve_certificate >/dev/null"
-    local query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
-    juju ssh $mch "$login_cmd && $query_cmd" | grep "Capacity alert thresholds" | awk '{print$5}' | grep -q "$high_alert" >/dev/null
-    juju ssh $mch "$login_cmd && $query_cmd" | grep "Capacity alert thresholds" | awk '{print$7}' | grep -q "$critical_alert" >/dev/null
-    echo "INFO: Success. Capacity alert thresholds: high is $high_alert, critical is $critical_alert"
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+  juju ssh $mch "$login_cmd && $query_cmd" | grep "Capacity alert thresholds" | awk '{print$5}' | grep -q "$high_alert"
+  juju ssh $mch "$login_cmd && $query_cmd" | grep "Capacity alert thresholds" | awk '{print$7}' | grep -q "$critical_alert"
+  echo "INFO: Success. Capacity alert thresholds: high is $high_alert, critical is $critical_alert"
 }
 
 function check_path {
-    local mch=${machines[$1]}
-    local path_type=$2
-    local device_path=$3
+  mch=${machines[$1]}
+  path_type=$2
+  local device_path=$3
 
-    local username='admin'
-    local password=`get_config password`
+  username='admin'
+  password=`get_config fuel-master password`
 
-    local login_cmd="scli --login --username $username --password $password --approve_certificate >/dev/null"
-    sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds"| grep 'SDS ID:' | awk '{print$5}'`)
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds"| grep 'SDS ID:' | awk '{print$5}'`)
 
-    for sds_name in ${sds_names[@]} ; do
-      output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
-      if ! echo "$output_sds" | grep "$path_type" | grep -q 'total 1 devices'  ; then
-        echo "ERROR: ($my_name:$LINENO) Unexpected number of devices."
-        echo "$output_sds" | grep "$path_type"
-        return 1
-      elif ! echo "$output_sds" | sed -n "/$path_type/{n;p;}" | grep -q "$device_path" ; then
-        echo "ERROR: ($my_name:$LINENO) Path of $path_type on $sds_name isn't $device_path"
-        echo "$output_sds" | sed -n "/$path_type/{n;p;}"
-        return 1
-      else
-        echo "INFO: Success. Path of $path_type on $sds_name is $device_path."
-      fi
-    done
+  for sds_name in ${sds_names[@]} ; do
+    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
+    if ! echo "$output_sds" | grep "$path_type" | grep -q 'total 1 devices'  ; then
+      echo "ERROR: ($my_name:$LINENO) Unexpected number of devices."
+      echo "$output_sds" | grep "$path_type"
+      return 1
+    elif ! echo "$output_sds" | sed -n "/$path_type/{n;p;}" | grep -q "$device_path" ; then
+      echo "ERROR: ($my_name:$LINENO) Path of $path_type on $sds_name isn't $device_path"
+      echo "$output_sds" | sed -n "/$path_type/{n;p;}"
+      return 1
+    else
+      echo "INFO: Success. Path of $path_type on $sds_name is $device_path."
+    fi
+  done
 }
 
 function check_protection_domain {
-    local mch=${machines[$1]}
-    local pd_name=$2
+  mch=${machines[$1]}
+  pd_name=$2
 
-    local username='admin'
-    local password=`get_config password`
+  username='admin'
+  password=`get_config fuel-master password`
 
-    local login_cmd="scli --login --username $username --password $password --approve_certificate >/dev/null"
-    output_sds=`juju ssh $mch "$login_cmd && scli --query_all_sds 2>/dev/null"`
-    if echo $output_sds | grep 'Protection Domain' | grep $pd_name  ; then
-      echo "INFO: Success. Protection domain name is $pd_name"
-    else
-      echo "ERROR: Wrong protection domain name."
-      echo $output_sds | grep 'Protection Domain'
-      return 1
-    fi
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  output_sds=`juju ssh $mch "$login_cmd && scli --query_all_sds"`
+  if echo $output_sds | grep 'Protection Domain' | grep $pd_name  ; then
+    echo "INFO: Success. Protection domain name is $pd_name"
+  else
+    echo "ERROR: Wrong protection domain name."
+    echo $output_sds | grep 'Protection Domain'
+    return 1
+  fi
 }
 
 function check_password {
-  local mch=${machines[$1]}
-  local password=$2
+  mch=${machines[$1]}
+  password=$2
 
-  local username='admin'
-  if juju ssh $mch "scli --login --username $username --password $2 --approve_certificate >/dev/null" ; then
-      echo "INFO: Success. Password was changed to $current_password"
+  username='admin'
+  if juju ssh $mch "scli --login --username $username --password $2 --approve_certificate" ; then
+    echo "INFO: Success. Password was changed to $password"
   else
     echo "ERROR: Wrong password. Please check."
     return 1
@@ -295,23 +292,23 @@ function check_password {
 }
 
 function check_sp_name {
-    local mch=${machines[$1]}
-    local sp_name=$2
+  mch=${machines[$1]}
+  sp_name=$2
 
-    local username='admin'
-    local password=`get_config password`
+  username='admin'
+  password=`get_config fuel-master password`
 
-    local login_cmd="scli --login --username $username --password $password --approve_certificate >/dev/null"
-    sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds"| grep 'SDS ID:' | awk '{print$5}'`)
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds"| grep 'SDS ID:' | awk '{print$5}'`)
 
-    for sds_name in ${sds_names[@]} ; do
-      output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
-      if ! echo "$output_sds" | grep -A 3 "Device information " | grep 'Storage Pool:' | grep -q $sp_name  ; then
-        echo "ERROR: Unexpected name of storage pool."
-        echo "$output_sds" | grep -A 3 "Device information"
-        return 1
-      else
-        echo "INFO: Success. Storage pool name is $sp_name."
-      fi
-    done
+  for sds_name in ${sds_names[@]} ; do
+    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
+    if ! echo "$output_sds" | grep -A 3 "Device information " | grep 'Storage Pool:' | grep -q $sp_name  ; then
+      echo "ERROR: Unexpected name of storage pool."
+      echo "$output_sds" | grep -A 3 "Device information"
+      return 1
+    else
+      echo "INFO: Success. Storage pool name is $sp_name."
+    fi
+  done
 }
