changed sds storage pool test and rfcache test to get list of parameters (#21)
* changed sds storage pool test and rfcache test to get list of parameters

* fixed style

* fixed check_storage_pool check_capacity_alerts and check_rfcache

* fixed returns, added check_specific_storage_pool

* Update deploy-fuel.sh

* Update functions

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -17,7 +17,7 @@ if [[ "${cloud}" == "gce" ]]; then
   device_paths="/var/scaleio_disk"
 else
   device_paths="/dev/xvdf"
-  rfcache_path="/dev/xvdg"
+  rfcache_paths="/dev/xvdh,/dev/xvdi"
 fi
 machines=()
 deploy_counter=1
@@ -31,7 +31,7 @@ function provision_machines() {
   echo "Provision machines: $*"
   while (( "$#" )); do
     # TODO: Change create machine to use google
-    local mx=$(create_machine 2 2)
+    local mx=$(create_machine 2 4)
     echo "Machine $1 created: $mx"
     machines[$1]=${mx}
     new_mx+=(${mx})
@@ -213,20 +213,67 @@ function check_storage_pool {
   key_to_check=$2
   expected_value=$3
 
-  sp=`get_config fuel-master storage-pools`
+  storage_pools=`get_config fuel-master storage-pools`
+  sp_list=`echo "$storage_pools" | sed 's/,/ /'`
   pd=`get_config fuel-master protection-domain`
   username='admin'
   password=`get_config fuel-master password`
 
   login_cmd="scli --login --username $username --password $password --approve_certificate"
-  query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
-  if output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null | grep "$key_to_check" | grep -q "$expected_value"` ; then
-    echo "INFO: Success. Parameter $key_to_check is $expected_value."
-  else
-    echo "ERROR: Parameter $key_to_check is in wrong state."
-    echo "$output"
-    return 1
-  fi
+  ret=0
+  for sp in $sp_list ; do
+    query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+    output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null`
+    if echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
+      echo "INFO: Success. Parameter $key_to_check in storage pool $sp is $expected_value."
+    else
+      echo "ERROR: Parameter $key_to_check in storage pool $sp is in wrong state."
+      echo "$output"
+      ((++ret))
+    fi
+  done
+
+  return $ret
+}
+
+function check_specific_storage_pool {
+  mch=${machines[$1]}
+  key_to_check=$2
+  expected_value=$3
+  storage_pools=`get_config fuel-master storage-pools`
+  checked_sps=${4:-"$storage_pools"}
+
+  sp_list=`echo "$storage_pools" | sed 's/,/ /g'`
+  checked_sp_list=(`echo "$checked_sps" | sed 's/,/ /g'`)
+  pd=`get_config fuel-master protection-domain`
+  username='admin'
+  password=`get_config fuel-master password`
+
+  ret=0
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  for sp in $sp_list ; do
+    query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+    output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null`
+    if [[ ${checked_sp_list[@]} =~ "$sp" ]] ; then
+      if echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
+        echo "INFO: Success. Parameter $key_to_check in storage pool $sp is $expected_value."
+      else
+        echo "ERROR: Parameter $key_to_check in storage pool $sp is in wrong state."
+        echo "$output"
+        ((++ret))
+      fi
+    else
+      if ! echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
+        echo "INFO: Success. Parameter $key_to_check in storage pool $sp is not in state $expected_value."
+      else
+        echo "ERROR: Parameter $key_to_check in storage pool $sp is in $expected_value, but shouldn't."
+        echo "$output"
+        ((++ret))
+      fi
+    fi
+  done
+
+  return $ret
 }
 
 function check_capacity_alerts {
@@ -234,33 +281,40 @@ function check_capacity_alerts {
   high_alert=$2
   critical_alert=$3
 
-  sp=`get_config fuel-master storage-pools`
+  storage_pools=`get_config fuel-master storage-pools`
+  sp_list=`echo "$storage_pools" | sed 's/,/ /g'`
   pd=`get_config fuel-master protection-domain`
   username='admin'
   password=`get_config fuel-master password`
 
+  ret=0
   login_cmd="scli --login --username $username --password $password --approve_certificate"
-  query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
-  output_storage_pool=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null | grep "Capacity alert thresholds"`
-  if echo "$output_storage_pool" | awk '{print$5}' | grep -q "$high_alert" ; then
-    if echo "$output_storage_pool" | awk '{print$7}' | grep -q "$critical_alert" ; then
-      echo "INFO: Success. Capacity alert thresholds: high is $high_alert, critical is $critical_alert"
+  for sp in $sp_list ; do
+    query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+    output_storage_pool=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null | grep "Capacity alert thresholds"`
+    if echo "$output_storage_pool" | awk '{print$5}' | grep -q "$high_alert" ; then
+       echo "INFO: Success. Capacity alert thresholds on $sp storage pool: high is $high_alert."
     else
-      echo "ERROR: Wrong capacity critical alert thresholds"
+      echo "ERROR: Wrong capacity high alert thresholds on $sp storage pool."
       echo "$output_storage_pool"
-      return 1
+      ((++ret))
     fi
-  else
-    echo "ERROR: Wrong capacity alert thresholds"
-    echo "$output_storage_pool"
-    return 1
-  fi
+    if echo "$output_storage_pool" | awk '{print$7}' | grep -q "$critical_alert" ; then
+      echo "INFO: Success. Capacity alert thresholds on $sp storage pool: critical is $critical_alert"
+    else
+      echo "ERROR: Wrong capacity critical alert thresholds on $sp storage pool."
+      echo "$output_storage_pool"
+      ((++ret))
+    fi
+  done
+
+  return $ret
 }
 
-function check_path {
+function check_rfcache {
   mch=${machines[$1]}
-  path_type=$2
-  local device_path=$3
+  rfcache_list=(`echo $2 | sed 's/,/ /g'`)
+  rfcache_count=${#rfcache_list[@]}
 
   username='admin'
   password=`get_config fuel-master password`
@@ -268,20 +322,26 @@ function check_path {
   login_cmd="scli --login --username $username --password $password --approve_certificate"
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null| grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
-    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
-    if ! echo "$output_sds" | grep "$path_type" | grep -q 'total 1 devices'  ; then
+    rfcache_output=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null | grep "Rfcache device information" -A $(($rfcache_count*2+1))`
+    if ! echo "$rfcache_output" | grep -q "total $rfcache_count devices"  ; then
       echo "ERROR: Unexpected number of devices on $sds_name."
-      echo "$output_sds" | grep "$path_type"
-      return 1
-    elif ! echo "$output_sds" | sed -n "/$path_type/{n;p;}" | grep -q "$device_path" ; then
-      echo "ERROR: Path of $path_type on $sds_name isn't $device_path"
-      echo "$output_sds" | sed -n "/$path_type/{n;p;}"
-      return 1
-    else
-      echo "INFO: Success. Path of $path_type on $sds_name is $device_path."
+      echo "$rfcache_output" | grep "Rfcache device information"
+      ((++ret))
     fi
+    for rfcache in ${rfcache_list[@]} ; do
+      if ! echo "$rfcache_output" | grep -q $rfcache ; then
+        echo "ERROR: No $rfcache RFCache path on $sds_name"
+        echo "$rfcache_output"
+        ((++ret))
+      else
+        echo "INFO: Success. There is $rfcache RFCache path of on $sds_name."
+      fi
+    done
   done
+
+  return $ret
 }
 
 function check_protection_domain {
@@ -295,34 +355,41 @@ function check_protection_domain {
 
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null | grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
     output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
     if ! echo "$output_sds" | grep 'Protection Domain:' | grep -q $pd_name  ; then
       echo "ERROR: Wrong protection domain on $sds_name."
       echo "$output_sds" | grep "Protection Domain:"
-      return 1
+      ((++ret))
     else
       echo "INFO: Success. Protection domain on $sds_name is $pd_name."
     fi
   done
+
+  return $ret
 }
 
 function check_password {
   mch=${machines[$1]}
   password=$2
 
+  ret=0
   username='admin'
   if juju ssh $mch "scli --login --username $username --password $2 --approve_certificate" 2>/dev/null ; then
     echo "INFO: Success. Password was changed to $password"
   else
     echo "ERROR: Wrong password. Please check."
-    return 1
+    ((++ret))
   fi
+
+  return $ret
 }
 
-function check_sp_name {
+function check_sds_storage_pool {
   mch=${machines[$1]}
-  sp_name=$2
+  sp_list=(`echo $2 | sed 's/,/ /g'`)
+  device_paths_list=(`echo $3 | sed 's/,/ /g'`)
 
   username='admin'
   password=`get_config fuel-master password`
@@ -330,16 +397,31 @@ function check_sp_name {
   login_cmd="scli --login --username $username --password $password --approve_certificate"
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null | grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
-    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null`
-    if ! echo "$output_sds" | grep -A 3 "Device information " | grep 'Storage Pool:' | grep -q $sp_name  ; then
-      echo "ERROR: Unexpected name of storage pool on $sds_name."
-      echo "$output_sds" | grep -A 3 "Device information"
-      return 1
-    else
-      echo "INFO: Success. Storage pool name on $sds_name is $sp_name."
+    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
+    if ! echo "$output_sds" | grep "Device information" | grep -q "total ${#device_paths_list[@]} devices" ; then
+      echo "ERROR: Error in devices number in $sds_name"
+      echo "$output_sds"
+      ((++ret))
     fi
+    i=0
+    for devpath in $device_paths_list ; do
+      if ! device_info=`echo "$output_sds" | grep -A 2 "$devpath"`  ; then
+        echo "ERROR: Not found expected $devpath device path on $sds_name."
+        echo "$output_sds"
+        ((++ret))
+      elif ! echo "$device_info" | grep -q ${sp_list[$i]} ; then
+        echo "ERROR: Wrong storage pool on $devpath on $sds_name. Expected ${sp_list[$i]}."
+        echo "$device_info"
+        ((++ret))
+      fi
+      echo "INFO: Success. There is ${sp_list[$i]} storage pool on $devpath on $sds_name."
+      ((++i))
+     done
   done
+
+  return $ret
 }
 
 function check_fuel_perfomance {
