fixed returns, added check_specific_storage_pool

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -212,16 +212,15 @@ function check_storage_pool {
   mch=${machines[$1]}
   key_to_check=$2
   expected_value=$3
-  storage_pools=`get_config fuel-master storage-pools`
-  checked_sps=${4:-"$storage_pools"}
 
-  sp_list=`echo "$checked_sps" | sed 's/,/ /g'`
+  storage_pools=`get_config fuel-master storage-pools`
+  sp_list=`echo "$storage_pools" | sed 's/,/ /'`
   pd=`get_config fuel-master protection-domain`
   username='admin'
   password=`get_config fuel-master password`
 
-  ret=0
   login_cmd="scli --login --username $username --password $password --approve_certificate"
+  ret=0
   for sp in $sp_list ; do
     query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
     output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null`
@@ -233,6 +232,47 @@ function check_storage_pool {
       ((++ret))
     fi
   done
+
+  return $ret
+}
+
+function check_specific_storage_pool {
+  mch=${machines[$1]}
+  key_to_check=$2
+  expected_value=$3
+  storage_pools=`get_config fuel-master storage-pools`
+  checked_sps=${4:-"$storage_pools"}
+
+  sp_list=`echo "$storage_pools" | sed 's/,/ /g'`
+  checked_sp_list=(`echo "$checked_sps" | sed 's/,/ /g'`)
+  pd=`get_config fuel-master protection-domain`
+  username='admin'
+  password=`get_config fuel-master password`
+
+  ret=0
+  login_cmd="scli --login --username $username --password $password --approve_certificate"
+  for sp in $sp_list ; do
+    query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
+    output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null`
+    if [[ ${checked_sp_list[@]} =~ "$sp" ]] ; then
+      if echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
+        echo "INFO: Success. Parameter $key_to_check in storage pool $sp is $expected_value."
+      else
+        echo "ERROR: Parameter $key_to_check in storage pool $sp is in wrong state."
+        echo "$output"
+        ((++ret))
+      fi
+    else
+      if ! echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
+        echo "INFO: Success. Parameter $key_to_check in storage pool $sp is not in state $expected_value."
+      else
+        echo "ERROR: Parameter $key_to_check in storage pool $sp is in $expected_value, but shouldn't."
+        echo "$output"
+        ((++ret))
+      fi
+    fi
+  done
+
   return $ret
 }
 
@@ -273,7 +313,7 @@ function check_capacity_alerts {
 
 function check_rfcache {
   mch=${machines[$1]}
-  rfcache_list=($2)
+  rfcache_list=(`echo $2 | sed 's/,/ /g'`)
   rfcache_count=${#rfcache_list[@]}
 
   username='admin'
@@ -282,23 +322,26 @@ function check_rfcache {
   login_cmd="scli --login --username $username --password $password --approve_certificate"
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null| grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
     rfcache_output=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null | grep "Rfcache device information" -A $(($rfcache_count*2+1))`
     if ! echo "$rfcache_output" | grep -q "total $rfcache_count devices"  ; then
       echo "ERROR: Unexpected number of devices on $sds_name."
       echo "$rfcache_output" | grep "Rfcache device information"
-      return 1
+      ((++ret))
     fi
     for rfcache in ${rfcache_list[@]} ; do
       if ! echo "$rfcache_output" | grep -q $rfcache ; then
         echo "ERROR: No $rfcache RFCache path on $sds_name"
         echo "$rfcache_output"
-        return 1
+        ((++ret))
       else
         echo "INFO: Success. There is $rfcache RFCache path of on $sds_name."
       fi
     done
   done
+
+  return $ret
 }
 
 function check_protection_domain {
@@ -312,29 +355,35 @@ function check_protection_domain {
 
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null | grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
     output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
     if ! echo "$output_sds" | grep 'Protection Domain:' | grep -q $pd_name  ; then
       echo "ERROR: Wrong protection domain on $sds_name."
       echo "$output_sds" | grep "Protection Domain:"
-      return 1
+      ((++ret))
     else
       echo "INFO: Success. Protection domain on $sds_name is $pd_name."
     fi
   done
+
+  return $ret
 }
 
 function check_password {
   mch=${machines[$1]}
   password=$2
 
+  ret=0
   username='admin'
   if juju ssh $mch "scli --login --username $username --password $2 --approve_certificate" ; then
     echo "INFO: Success. Password was changed to $password"
   else
     echo "ERROR: Wrong password. Please check."
-    return 1
+    ((++ret))
   fi
+
+  return $ret
 }
 
 function check_sds_storage_pool {
@@ -348,26 +397,29 @@ function check_sds_storage_pool {
   login_cmd="scli --login --username $username --password $password --approve_certificate"
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null | grep 'SDS ID:' | awk '{print$5}'`)
 
+  ret=0
   for sds_name in ${sds_names[@]} ; do
     output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
     if ! echo "$output_sds" | grep "Device information" | grep -q "total ${#device_paths_list[@]} devices" ; then
       echo "ERROR: Error in devices number in $sds_name"
       echo "$output_sds"
-      return 1
+      ((++ret))
     fi
     i=0
     for devpath in $device_paths_list ; do
       if ! device_info=`echo "$output_sds" | grep -A 2 "$devpath"`  ; then
         echo "ERROR: Not found expected $devpath device path on $sds_name."
         echo "$output_sds"
-        return 1
+        ((++ret))
       elif ! echo "$device_info" | grep -q ${sp_list[$i]} ; then
-        echo "ERROR: Wrong storage pool on $devpath on $sds_name."
+        echo "ERROR: Wrong storage pool on $devpath on $sds_name. Expected ${sp_list[$i]}."
         echo "$device_info"
-        return 1
+        ((++ret))
       fi
       echo "INFO: Success. There is ${sp_list[$i]} storage pool on $devpath on $sds_name."
       ((++i))
      done
   done
+
+  return $ret
 }
