fixed style

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -214,13 +214,13 @@ function check_storage_pool {
   expected_value=$3
 
   storage_pools=`get_config fuel-master storage-pools`
-  sp_list=(`echo "$storage_pools" | sed 's/,/ /'`)
+  sp_list=`echo "$storage_pools" | sed 's/,/ /g'`
   pd=`get_config fuel-master protection-domain`
   username='admin'
   password=`get_config fuel-master password`
 
   login_cmd="scli --login --username $username --password $password --approve_certificate"
-  for sp in "${sp_list[@]}" ; do
+  for sp in $sp_list ; do
     query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
     output=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null`
     if echo "$output" | grep "$key_to_check" | grep -q "$expected_value" ; then
@@ -239,13 +239,13 @@ function check_capacity_alerts {
   critical_alert=$3
 
   storage_pools=`get_config fuel-master storage-pools`
-  sp_list=(`echo "$storage_pools" | sed 's/,/ /'`)
+  sp_list=`echo "$storage_pools" | sed 's/,/ /g'`
   pd=`get_config fuel-master protection-domain`
   username='admin'
   password=`get_config fuel-master password`
 
   login_cmd="scli --login --username $username --password $password --approve_certificate"
-  for sp in "${sp_list[@]}" ; do
+  for sp in $sp_list ; do
     query_cmd="scli --query_storage_pool --protection_domain_name $pd --storage_pool_name $sp"
     output_storage_pool=`juju ssh $mch "$login_cmd && $query_cmd" 2>/dev/null | grep "Capacity alert thresholds"`
     if echo "$output_storage_pool" | awk '{print$5}' | grep -q "$high_alert" ; then
@@ -267,7 +267,7 @@ function check_capacity_alerts {
 function check_rfcache {
   mch=${machines[$1]}
   rfcache_list=($2)
-  rfcache_number=${#rfcache_list[@]}
+  rfcache_count=${#rfcache_list[@]}
 
   username='admin'
   password=`get_config fuel-master password`
@@ -276,8 +276,8 @@ function check_rfcache {
   sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null| grep 'SDS ID:' | awk '{print$5}'`)
 
   for sds_name in ${sds_names[@]} ; do
-    rfcache_output=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null | grep "Rfcache device information" -A (( $rfcache_number*2+1 ))`
-    if ! echo "$rfcache_output" | grep -q "total $rfcache_number devices"  ; then
+    rfcache_output=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name" 2>/dev/null | grep "Rfcache device information" -A (( $rfcache_count*2+1 ))`
+    if ! echo "$rfcache_output" | grep -q "total $rfcache_count devices"  ; then
       echo "ERROR: Unexpected number of devices on $sds_name."
       echo "$rfcache_output" | grep "Rfcache device information"
       return 1
@@ -332,8 +332,8 @@ function check_password {
 
 function check_sds_storage_pool {
   mch=${machines[$1]}
-  sp_list=($2)
-  device_paths_list=($3)
+  sp_list=(`echo $2 | sed 's/,/ /g'`)
+  device_paths_list=`echo $3 | sed 's/,/ /g'`
 
   username='admin'
   password=`get_config fuel-master password`
@@ -349,17 +349,15 @@ function check_sds_storage_pool {
       return 1
     fi
     i=0
-    for devpath in ${device_paths_list[@]} ; do
+    for devpath in $device_paths_list ; do
       if ! device_info=`echo "$output_sds" | grep -A 2 "$devpath"`  ; then
         echo "ERROR: Not found expected $devpath device path on $sds_name."
         echo "$output_sds"
         return 1
-      else
-        if ! echo "$device_info" | grep -q ${sp_list[$i]} ; then
-          echo "ERROR: Wrong storage pool on $devpath on $sds_name."
-          echo "$device_info"
-          return 1
-        fi
+      elif ! echo "$device_info" | grep -q ${sp_list[$i]} ; then
+        echo "ERROR: Wrong storage pool on $devpath on $sds_name."
+        echo "$device_info"
+        return 1
       fi
       echo "INFO: Success. There is ${sp_list[$i]} storage pool on $devpath on $sds_name."
       ((++i))
