added opportunity to choose branch of fuel-plugin-scaleio (#17)
* added opportunity to choose branch of fuel-plugin-scaleio

do not merge until merging branch-name parameter in fuel-charms
repository

* fixed write to /tmp/config.yaml

* changed check_protection_domain to check each sds

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -22,6 +22,8 @@ fi
 machines=()
 deploy_counter=1
 
+branch=${BRANCH:-"master"}
+
 trap 'catch_errors $LINENO' ERR
 
 function provision_machines() {
@@ -122,8 +124,10 @@ function remove_node_service() {
 
 function prepare_fuel_master() {
   mch=${machines[$1]}
-  juju deploy local:trusty/fuel-master --to $mch
-  juju set fuel-master device-paths=${device_paths}
+  echo "fuel-master:
+    branch-name:  $branch
+    device-paths: $device_paths" >/tmp/config.yaml
+  juju deploy local:trusty/fuel-master --to $mch --config /tmp/config.yaml
 }
 
 function set_fuel_options() {
@@ -134,8 +138,11 @@ function deploy_node_service() {
   mch=${machines[$1]}
   name=fuel-node${mch}
   roles=$2
-  if ! juju service get ${name} ; then
-    juju deploy local:trusty/fuel-node $name --to $mch
+
+  if ! juju service get ${name} 2>/dev/null  ; then
+    echo "$name:
+      branch-name:  $branch" >/tmp/config.yaml
+    juju deploy local:trusty/fuel-node $name --to $mch --config /tmp/config.yaml
     juju add-relation fuel-master $name
   fi
   juju set $name roles="${roles}"
@@ -285,14 +292,19 @@ function check_protection_domain {
   password=`get_config fuel-master password`
 
   login_cmd="scli --login --username $username --password $password --approve_certificate"
-  output_sds=`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null`
-  if echo $output_sds | grep 'Protection Domain' | grep $pd_name  ; then
-    echo "INFO: Success. Protection domain name is $pd_name"
-  else
-    echo "ERROR: Wrong protection domain name."
-    echo $output_sds | grep 'Protection Domain'
-    return 1
-  fi
+
+  sds_names=(`juju ssh $mch "$login_cmd && scli --query_all_sds" 2>/dev/null | grep 'SDS ID:' | awk '{print$5}'`)
+
+  for sds_name in ${sds_names[@]} ; do
+    output_sds=`juju ssh $mch "$login_cmd && scli --query_sds --sds_name $sds_name"`
+    if ! echo "$output_sds" | grep 'Protection Domain:' | grep -q $pd_name  ; then
+      echo "ERROR: Wrong protection domain on $sds_name."
+      echo "$output_sds" | grep "Protection Domain:"
+      return 1
+    else
+      echo "INFO: Success. Protection domain on $sds_name is $pd_name."
+    fi
+  done
 }
 
 function check_password {
