added test for check installed branch of fuel-plugin-scaleio (#32)
* added test for check installed branch of fuel-plugin-scaleio

* simplified check_branch

diff --git a/juju/fuel/functions b/juju/fuel/functions
--- a/juju/fuel/functions
+++ b/juju/fuel/functions
@@ -531,3 +531,34 @@ function check_scaleio_not_installed {
     echo "INFO: Success. ScaleIO packages wasn't installed to controller."
   fi
 }
+
+function check_branch {
+  mch=${machines[$1]}
+
+  branch=`get_config fuel-master branch-name`
+
+  master_file=' deployment_tasks.yaml'
+  branch_file=' tasks.yaml'
+
+  files="sudo ls -l /root/fuel-plugin-scaleio"
+
+  if [[ $branch == "master" ]] ; then
+    present_file=$master_file
+    absent_file=$branch_file
+  else
+    present_file=$branch_file
+    absent_file=$master_file
+  fi
+
+  if juju ssh $mch "$files" 2>/dev/null | grep "$present_file" ; then
+    if ! juju ssh $mch "$files" 2>/dev/null | grep "$absent_file" ; then
+      echo "INFO: Success. Your branch is $branch. All files are corresponding."
+    else
+      echo "ERROR: Your branch is $branch. There is unexpected file $absent_file in /root/fuel-plugin-scaleio."
+      return 1
+    fi
+  else
+    echo "ERROR: Your branch is $branch. There is no expected file $present_file in /root/fuel-plugin-scaleio."
+    return 1
+  fi
+}
